stages:
    - lint
    - test
    - coverage
    - deploy

.composer_cache: &composer_cache
    cache:
        paths:
            - vendor/

.install_dependencies: &install_dependencies
    before_script:
        - composer install --prefer-dist --classmap-authoritative --no-interaction --no-progress

.composer_test: &composer_test
    script:
        - composer test

phpstan:
    image: $CI_REGISTRY/mathew-davies/dockerimages/php:7.1
    stage: lint
    <<: *install_dependencies
    <<: *composer_cache
    script:
        - composer lint

php 7.0:
    image: $CI_REGISTRY/mathew-davies/dockerimages/php:7.0
    stage: test
    <<: *install_dependencies
    <<: *composer_test
    <<: *composer_cache

php 7.1:
    image: $CI_REGISTRY/mathew-davies/dockerimages/php:7.1
    stage: test
    <<: *install_dependencies
    <<: *composer_test
    <<: *composer_cache

php 7.2:
    image: $CI_REGISTRY/mathew-davies/dockerimages/php:7.2
    stage: test
    <<: *install_dependencies
    <<: *composer_test
    <<: *composer_cache

coverage:
    image: $CI_REGISTRY/mathew-davies/dockerimages/php:7.1
    stage: coverage
    <<: *install_dependencies
    <<: *composer_cache
    script:
        - composer coverage
    artifacts:
        paths:
          - coverage/

pages:
    stage: deploy
    dependencies:
        - coverage
    script:
        - mv coverage/ public/
    artifacts:
        expire_in: 30 days
        paths:
            - public
    only:
        - master

