services:

    Thepixeldeveloper\Sitemap\ChunkedUrlset: ~
    Thepixeldeveloper\Sitemap\Drivers\XmlWriterDriver: ~

    Thepixeldeveloper\SitemapBundle\Dumper\SitemapDumper:
        autowire: true

    Thepixeldeveloper\SitemapBundle\Command\SitemapDumperCommand:
        autowire: true
        autoconfigure: true
