services:

    Thepixeldeveloper\Sitemap\ChunkedUrlset: ~
    Thepixeldeveloper\Sitemap\Drivers\XmlWriterDriver: ~

    Thepixeldeveloper\SitemapBundle\Dumper\SitemapDumper:
        autowire: true
        arguments:
            $driver: "@Thepixeldeveloper\Sitemap\Drivers\XmlWriterDriver"

    Thepixeldeveloper\SitemapBundle\Command\SitemapDumperCommand:
        autowire: true
        autoconfigure: true
        arguments:
            $dumper: "@Thepixeldeveloper\SitemapBundle\Dumper\SitemapDumper"
